name: "docker-build"
description: "Build and publish a docker image to GHCR"

inputs:
  go-version:  # id of input
    description: 'Go version to build the docker image with'
    required: false
    default: 1.19

runs:
  using: "composite"
  steps:
    - name: "Checkout source code"
      uses: "actions/checkout@v3"
    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: ${{ inputs.go-version }}
    - name: "Build"
      run: "make build"
    # - name: Set up QEMU
    #   uses: docker/setup-qemu-action@v2
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    - name: Login to GHCR
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: tag version
      uses: nowsprinting/check-version-format-action@v3
      id: tag_version
      with:
        prefix: 'v'
    - name: Build and push
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: |
          ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest
          ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ steps.version.outputs.full }}
        file: Dockerfile
