name: "docker-build-ephemeral"
description: "Build and publish a docker image for the ephemeral cluster to GHCR"

inputs:
  go-version:  # id of input
    description: 'Go version to build the docker image with'
    required: true
    default: 'World'

runs:
  using: "composite"
  steps:
    - name: "Checkout source code"
      uses: "actions/checkout@v3"
    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.18
    - name: "Build"
      run: "make build"
    # - name: Set up QEMU
    #   uses: docker/setup-qemu-action@v2
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    - name: Login to GHCR
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Build and push
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: ghcr.io/celestiaorg/celestia-app-ephemeral:latest
        file: docker/Dockerfile_ephemeral