name: Housekeeping

on:
  # triage new issues
  issues:
    types: [opened]
  pull_request:

env:
  PROJECT_URL: "https://github.com/orgs/celestiaorg/projects/10"

jobs:
  # calls housekeeping for issues
  # In this example, we are adding `needs: triage` label to all newly created
  # and unlabeled issues. Additionally, the section that is commented out would
  # be adding all issues to the defined project
  issues:
    name: Issue Management
    if: ${{ github.event_name == 'issues' }}
    uses: ./.github/workflows/reusable_housekeeping.yml
    secrets: inherit
    permissions:
      issues: write
    with:
      # Labels
      run-labels: true
      labels-to-add: "needs: triage"
      ignore-if-labeled: true
      # Projects
      # run-projects: true
      # project-url: ${{ env.PROJECT_URL }}

  # calls housekeeping for PRs
  # In this example, we are adding PRs with the `project` label to the defined
  # project board. Additionally we are using the custom PR assignment rules
  # defined in `.github/auto_request_review.yml`.
  pull_request:
    name: PR Management
    if: ${{ github.event_name == 'pull_request' }}
    uses: ./.github/workflows/reusable_housekeeping.yml
    secrets: inherit
    permissions:
      # write access for issues is needed because the called workflow requires
      # write access to issues
      issues: write
    with:
      # Projects
      run-projects: true
      project-url: ${{ env.PROJECT_URL }}
      project-labels: "project"
      # Reviewers
      run-auto-request-review: true
